repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.283
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.2.0
    hooks:
      - id: pydoclint
        args: [--config=pyproject.toml, -q]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--strict]
        files: .*py$
        additional_dependencies:
          [
            Flask==2.3.2,
            apig-wsgi==2.18.0,
            numpy==1.25.1,
            requests==2.31.0,
            types-beautifulsoup4==4.12.0.5,
            types-requests==2.31.0.2,
            types-Pillow==10.0.0.2,
            types-boto3===1.0.2,
            boto3==1.28.5,
            freezegun==1.2.2,
            pytest==7.4.0,
            pyopenssl==23.2.0,
            beautifulsoup4==4.12.2,
            markdownify==0.11.6,
            pillow==10.0.0,
          ]
