repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-json
          - id: check-toml
          - id: check-xml

    - repo: https://github.com/timothycrosley/isort
      rev: 5.10.1
      hooks:
          - id: isort

    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black

    - repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            additional_dependencies:
                [
                    flake8-bugbear==22.6.22,
                    flake8-builtins==1.5.3,
                    flake8-comprehensions==3.10.0,
                    flake8-deprecated==1.3,
                    flake8-docstrings==1.6.0,
                    flake8-eradicate==1.2.1,
                    flake8-plugin-utils==1.3.2,
                    flake8-polyfill==1.0.2,
                    flake8-pytest-style==1.6.0,
                    flake8-simplify==0.19.2,
                ]

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.4
      hooks:
        - id: bandit
          exclude: tests

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: "v0.961"
        hooks:
        -   id: mypy
            args: [--strict]
            additional_dependencies: 
                [
                    advent-of-code-ocr==1.0.0,
                    lambda-multiprocessing==0.3,
                    types-beautifulsoup4==4.11.3,
                    types-requests==2.28.0,
                    types-requests==2.28.0,
                    types-urllib3==1.26.16,
                    typing_extensions==4.2.0,
                    types-boto3===1.0.2,
                    types-toml==0.10.8,
                    freezegun==1.2.1,
                    pytest==7.1.2,
                    Flask==2.1.2,
                    apig-wsgi==2.14.0,
                    numpy==1.23.1,
                    requests==2.28.1,
                    Pillow==9.3.0,
                    types-pillow==9.3.0.2
                ]
