repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-json
          - id: check-toml
          - id: check-xml

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.283
      hooks:
        - id: ruff
          args: [ --fix, --exit-non-zero-on-fix ]

    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black

    - repo: https://github.com/jsh9/pydoclint
      rev: 0.2.0
      hooks:
        - id: pydoclint
          args: [--config=pyproject.toml, -q]

    - repo: local
      hooks:
        - id: mypy
          name: mypy all files
          entry: python -m mypy 
          language: system
          files: .*py$
