repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-json
          - id: check-toml
          - id: check-xml

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort

    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black

    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            additional_dependencies:
                [
                    flake8-bugbear==23.7.10,
                    flake8-builtins==1.5.3,
                    flake8-comprehensions==3.14.0,
                    flake8-deprecated==2.0.1,
                    flake8-docstrings==1.7.0,
                    flake8-eradicate==1.5.0,
                    flake8-plugin-utils==1.3.3,
                    flake8-polyfill==1.0.2,
                    flake8-pytest-style==1.7.2,
                    flake8-simplify==0.20.0
                ]

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.5
      hooks:
        - id: bandit
          exclude: tests

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: "v1.4.1"
        hooks:
        -   id: mypy
            args: [--strict]
            additional_dependencies: 
                [
                    types-beautifulsoup4==4.12.0.5,
                    types-requests==2.31.0.1,
                    types-urllib3==1.26.25.13,
                    typing_extensions==4.7.1,
                    types-boto3===1.0.2,
                    types-toml==0.10.8.6,
                    types-pillow==9.3.0.2,
                    boto3==1.28.5,
                    freezegun==1.2.2,
                    pytest==7.4.0,
                    pillow==10.0.0,
                    Flask==2.3.2,
                    apig-wsgi==2.18.0,
                    numpy==1.25.1,
                    requests==2.31.0,
                    lambda-multiprocessing==0.3
                ]
