# Define custom wheel directory
ARG WHEEL_DIR="/var/wheels/"

#
# Create the image 
#
FROM --platform=linux/arm64 pypy:3.10-7.3.12-bookworm

# Include global arg in this stage of the build
ARG WHEEL_DIR
RUN mkdir -p ${WHEEL_DIR}

# Update pip and setuptools
# RUN pip install --upgrade pip setuptools

# Install aws-lambda-cpp build dependencies
# RUN apt-get update && \
#     apt-get install -y \
#     g++ \
#     make \
#     cmake \
#     unzip \
#     libcurl4-openssl-dev

# Add the project files and install dependancies
COPY ./requirements.txt .
RUN pip wheel --wheel-dir ${WHEEL_DIR} requests==2.31.0
#RUN pip wheel --wheel-dir ${WHEEL_DIR} awslambdaric -r requirements.txt