AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  advent-of-code-python

  template for the Advent of Code Python API

Resources:
  AdventOfCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.app
      Runtime: python3.9
      Timeout: 60
      MemorySize: 2048
      FunctionUrlConfig:
        AuthType: NONE
