AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for the Advent of Code RESTful API

Resources:
  AdventOfCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      PackageType: Image
      Timeout: 300
      MemorySize: 2048
      Architectures:
      - arm64
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      DockerTag: AdventOfCodeFunction
      Dockerfile: Dockerfile
      DockerContext: .

Outputs:
  HelloWorldFunction:
    Description: "Advent of Code Function ARN"
    Value: !GetAtt AdventOfCodeFunction.Arn
  AdventOfCodeFunctionURL:
    Description: "Advent of Code Function URL HTTP endpoint"
    Value: !GetAtt AdventOfCodeFunctionUrl.FunctionUrl