on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint, Check and Test AoC package
    runs-on: ubuntu-latest
    steps:
      - name: Check out Respository
        uses: actions/checkout@v3
      
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-bandit flake8-black flake8-isort flake8-bugbear flake8-deprecated
          pip install pytest pytest-xdist pytest-cov
          pip install mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Static type check with mypy
        run: |
          mypy --strict ./advent_of_code/
      
      - name: Testing with pytest
        run: |
          pytest -n auto --cov --cov-report=xml:coverage.xml

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ env.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml

  deploy-to-aws-lambda:
    name: Deploy AoC package to AWS Lambda
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out Respository
        uses: actions/checkout@v3
      
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v1
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
       
      - name: SAM build
        run: sam build
      
      - name: SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name advent-of-code-python --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1wh6zbny2z2lr --capabilities CAPABILITY_IAM --region eu-west-2

  test-aws:
    name: Test AWS Lambda
    needs: deploy-to-aws-lambda
    runs-on: ubuntu-latest
    steps:
      - name: Call lambda function
        run: |
          curl https://jnrxshzkvnbexzeedxptq54ugq0mqlpe.lambda-url.eu-west-2.on.aws
          curl https://jnrxshzkvnbexzeedxptq54ugq0mqlpe.lambda-url.eu-west-2.on.aws/2015
          curl https://jnrxshzkvnbexzeedxptq54ugq0mqlpe.lambda-url.eu-west-2.on.aws/2015/1
          curl https://jnrxshzkvnbexzeedxptq54ugq0mqlpe.lambda-url.eu-west-2.on.aws/2015/2/part_one
          curl https://jnrxshzkvnbexzeedxptq54ugq0mqlpe.lambda-url.eu-west-2.on.aws/2015/3/part_two