name: Compatability Check

on:
  push:
    branches:
      - main
      - dev

concurrency: 
  group: compatability${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Compatability Check
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Check out Respository
        uses: actions/checkout@v3
      
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      
      - name: Display python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_CI_CD_check.txt
          pip install -r requirements_CI_CD_test.txt

      - name: Lint with flake8
        if: ${{ always() }}
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Static type check with mypy
        if: ${{ always() }}
        run: |
          mypy --strict .
      
      - name: Testing with pytest
        if: ${{ always() }}
        run: |
          pytest ./tests/unit ./tests/integration -n auto --cov --cov-report term-missing:skip-covered

      - name: Security check with bandit
        if: ${{ always() }}
        run: |
          bandit -r advent_of_code