on: workflow_dispatch

jobs:
  compatability-testing:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 16
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11.0-alpha - 3.11.0']
    steps:
      - name: Check out Respository
        uses: actions/checkout@v3
      
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      
      - name: Display python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 flake8-bandit flake8-black flake8-isort flake8-bugbear flake8-deprecated
          pip install pytest pytest-xdist pytest-cov
          pip install mypy

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Static type check with mypy
        run: |
          mypy .
      
      - name: Testing with pytest
        run: |
          pytest -n auto --cov --cov-report term-missing:skip-covered
