name: Compatability Check

on:
  workflow_dispatch:

  pull_request:
    types: [opened, edited, reopened]

  push:
    branches:
      - main

concurrency: 
  group: compatability${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Compatability Check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']
    steps:
      - name: Check out Respository
        uses: actions/checkout@v3

      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      
      - name: Display python version
        run: python --version

      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key:
            requirements_dev.txt-${{ env.pythonLocation }}-${{ env.PYTHON_VERSION }}-${{hashFiles('requirements_dev.txt') }}

      - uses: actions/cache@v3
        name: Load dependancy cache
        id: requirements-dev-cache
        with:
          path: ~/.cache/pre-commit
          key:
            pre-commit-${{ env.pythonLocation }}-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install dependencies
        if: steps.requirements-dev-cache.outputs.cache-hit != 'true'
        run: pip install -r requirements_dev.txt

      - name: Install editable package
        if: steps.requirements-dev-cache.outputs.cache-hit != 'true'
        run: pip install --editable .

      - name: Run pre-commit on all files
        run: | 
          pip install pre-commit
          pre-commit run --all-files

      - name: Testing with pytest
        if: ${{ always() }}
        run: |
          pytest ./tests/unit ./tests/integration -n auto