name: Deploy-To-AWS-Lambda

on:
  workflow_dispatch:

concurrency: 
  group: Deploy${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-to-aws-lambda:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    steps:
      -  name: Check out respository
         uses: actions/checkout@v3

      - name: Set variables for Production
        if: github.ref == 'refs/heads/main'
        run: echo "SAM_CONFIG_FILE=samconfig.toml" >> $GITHUB_ENV
      
      - name: Set variables for Development
        if: github.ref == 'refs/heads/dev' || github.head_ref == 'dev'
        run: echo "SAM_CONFIG_FILE=samconfig_dev.toml" >> $GITHUB_ENV

      # - name: Setup up python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.11"
      #     cache: "pip"

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # - name: Install project dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: SAM Validate
        run: sam validate

      - name: SAM Build
        run: sam build --use-container --config-file ${{ env.SAM_CONFIG_FILE }}
    
      - name: SAM Deploy to AWS Lambda
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file ${{ env.SAM_CONFIG_FILE }}

      - name: Test Dev
        run: curl https://xfoq3sv7npeid5x6nzzlgdqqmy0uyesa.lambda-url.eu-west-2.on.aws

