name: Generate Test Durations

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    
concurrency: 
  group: duration${{github.ref}}
  cancel-in-progress: true

jobs:
  generate:
    name: Generate Durations
    runs-on: ubuntu-latest

    steps:
      - name: Check out Respository
        uses: actions/checkout@v3
      
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_CI_CD_test.txt
      
      - name: Run pytest
        run: pytest --clean-durations --store-durations -n auto
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
