name: Generate Test Durations

on:
  workflow_dispatch:
  
  schedule:
    - cron:  "23 1 * * 1"

  pull_request:
    types: [opened, edited, reopened]
    
concurrency: 
  group: duration${{github.ref}}
  cancel-in-progress: true

jobs:
  generate:
    name: Generate Durations
    runs-on: ubuntu-latest

    steps:
      - name: Check out Respository
        uses: actions/checkout@v3
        with:
          ref: dev
      
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt

      - name: Install editable package
        run: pip install --editable .

      - name: Run pytest
        run: pytest ./tests/unit ./tests/integration --cov --clean-durations --store-durations -n auto

      - name: Commit .test_duration file to respository      
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated .test_duration file
          branch: dev
