name: Update Status Graphic

on:
  workflow_dispatch:
  
  schedule:
    - cron:  "0 5 * 12 *"

  workflow_call:
    
concurrency: 
  group: status${{github.ref}}
  cancel-in-progress: true

jobs:
  generate:
    name: Updating Status Graphic
    runs-on: ubuntu-latest

    steps:
      - name: Check out Respository
        uses: actions/checkout@v3
        with:
          ref: dev
      
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt

      - name: Install editable package
        run: pip install --editable .[dev]

      - name: Generate status graphic
        run: python ./advent_of_code/utils/status_graphic.py

      - name: Commit status graphic file to respository      
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated status graphic
          branch: dev
