name: Update Status Graphic

on:
  workflow_dispatch:
  
  schedule:
    - cron:  "0 5 * 12 *"

  workflow_call:
    
concurrency: 
  group: status${{github.ref}}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.12

jobs:
  generate:
    name: Updating Status Graphic
    runs-on: ubuntu-latest

    steps:
      - name: Check out Respository
        uses: actions/checkout@v3
        with:
          ref: dev
      
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/cache@v4
        name: Load package cache
        id: package-cache
        with:
          path: ${{ env.pythonLocation }}
          key: pyproject.toml-${{ env.pythonLocation }}-${{ env.PYTHON_VERSION }}-${{hashFiles('pyproject.toml') }}

      - name: Install package
        if: steps.package-cache.outputs.cache-hit != 'true'
        run: pip install --editable .[dev]

      - name: Generate status graphic
        run: python ./advent_of_code/utils/status_graphic.py

      - name: Commit status graphic file to respository      
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated status graphic
          branch: dev
